package hu.bme.cryptochecker.modules.support

// The application supports 100 cryptocurrencies from the coins with highest market capitalization
enum class SupportedCurrencies(val coinName: String, val id: String) {
    BITCOIN("Bitcoin", "bitcoin"),
    ETHEREUM("Ethereum", "ethereum"),
    TETHER("Tether", "tether"),
    USD_COIN("USD Coin", "usd-coin"),
    BNB("BNB", "binancecoin"),
    XRP("XRP", "ripple"),
    BINANCE_USD("Binance USD", "binance-usd"),
    CARDANO("Cardano", "cardano"),
    SOLANA("Solana", "solana"),
    DOGECOIN("Dogecoin", "dogecoin"),
    POLKADOT("Polkadot", "polkadot"),
    WRAPPED_BITCOIN("Wrapped Bitcoin", "wrapped-bitcoin"),
    LIDO_STAKED_ETHER("Lido Staked Ether", "staked-ether"),
    AVALANCHE("Avalanche", "avalanche-2"),
    TRON("TRON", "tron"),
    SHIBA_INU("Shiba Inu", "shiba-inu"),
    DAI("Dai", "dai"),
    LEO_TOKEN("LEO Token", "leo-token"),
    LITECOIN("Litecoin", "litecoin"),
    CRONOS("Cronos", "crypto-com-chain"),
    POLYGON("Polygon", "matic-network"),
    NEAR_PROTOCOL("NEAR Protocol", "near"),
    FTX_TOKEN("FTX Token", "ftx-token"),
    BITCOIN_CASH("Bitcoin Cash", "bitcoin-cash"),
    STELLAR("Stellar", "stellar"),
    CHAINLINK("Chainlink", "chainlink"),
    OKB("OKB", "okb"),
    ALGORAND("Algorand", "algorand"),
    FLOW("Flow", "flow"),
    COSMOS_HUB("Cosmos Hub", "cosmos"),
    TERRA("Terra", "terra-luna"),
    ETHEREUM_CLASSIC("Ethereum Classic", "ethereum-classic"),
    MONERO("Monero", "monero"),
    UNISWAP("Uniswap", "uniswap"),
    APECOIN("ApeCoin", "apecoin"),
    VECHAIN("VeChain", "vechain"),
    HEDERA("Hedera", "hedera-hashgraph"),
    ELROND("Elrond", "elrond-erd-2"),
    THETA_FUEL("Theta Fuel", "theta-fuel"),
    TERRAUSD("TerraUSD", "terrausd"),
    INTERNET_COMPUTER("Internet Computer", "internet-computer"),
    MAGIC_INTERNET_MONEY("Magic Internet Money", "magic-internet-money"),
    DECENTRALAND("Decentraland", "decentraland"),
    FILECOIN("Filecoin", "filecoin"),
    CETH("cETH", "compound-ether"),
    AXIE_INFINITY("Axie Infinity", "axie-infinity"),
    THE_SANDBOX("The Sandbox", "the-sandbox"),
    DEFICHAIN("DeFiChain", "defichain"),
    FRAX("Frax", "frax"),
    TEZOS("Tezos", "tezos"),
    CHAIN("Chain", "chain-2"),
    THETA_NETWORK("Theta Network", "theta-token"),
    MAKER("Maker", "maker"),
    EOS("EOS", "eos"),
    TRUEUSD("TrueUSD", "true-usd"),
    PANCAKESWAP("PancakeSwap", "pancakeswap-token"),
    KUCOIN_TOKEN("KuCoin Token", "kucoin-shares"),
    CUSDC("cUSDC", "compound-usd-coin"),
    ZCASH("Zcash", "zcash"),
    HUOBI_BTC("Huobi BTC", "huobi-btc"),
    AAVE("Aave", "aave"),
    HUOBI_TOKEN("Huobi Token", "huobi-token"),
    KLAYTN("Klaytn", "klay-token"),
    THE_GRAPH("The Graph", "the-graph"),
    BITTORRENT("BitTorrent", "bittorrent"),
    BITCOIN_SV("Bitcoin SV", "bitcoin-cash-sv"),
    PAX_DOLLAR("Pax Dollar", "paxos-standard"),
    HELIUM("Helium", "helium"),
    THORCHAIN("THORChain", "thorchain"),
    IOTA("IOTA", "iota"),
    QUANT("Quant", "quant-network"),
    NEUTRINO_USD("Neutrino USD", "neutrino"),
    CDAI("cDAI", "cdai"),
    RADIX("Radix", "radix"),
    GATETOKEN("GateToken", "gatechain-token"),
    ECASH("eCash", "ecash"),
    STEPN("STEPN", "stepn"),
    BITDAO("BitDAO", "bitdao"),
    FANTOM("Fantom", "fantom"),
    NEXO("NEXO", "nexo"),
    NEO("NEO", "neo"),
    ARWEAVE("Arweave", "arweave"),
    ZILLIQA("Zilliqa", "zilliqa"),
    CONVEX_FINANCE("Convex Finance", "convex-finance"),
    WAVES("Waves", "waves"),
    CELO("Celo", "celo"),
    AMP("Amp", "amp-token"),
    GALA("Gala", "gala"),
    ENJIN_COIN("Enjin Coin", "enjincoin"),
    DASH("Dash", "dash"),
    KUSAMA("Kusama", "kusama"),
    PAX_GOLD("PAX Gold", "pax-gold"),
    CUSDT("cUSDT", "compound-usdt"),
    CHILIZ("Chiliz", "chiliz"),
    GNOSIS("Gnosis", "gnosis"),
    BASIC_ATTENTION_TOKEN("Basic Attention Token", "basic-attention-token"),
    FRAX_SHARE("Frax Share", "frax-share"),
    STACKS("Stacks", "blockstack"),
    LOOPRING("Loopring", "loopring"),
    SYNTHETIX_NETWORK_TOKEN("Synthetix Network Token", "havven")
}